version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=accounts_db
      - DB_USER=root
      - DB_PASSWORD=rootpassword
    volumes:
      - .:/var/www/project  # Весь проект
      - ./src:/var/www/html # Web-корень
    working_dir: /var/www/project
    networks:
      - app-network

  db:
    image: mysql:8.0-debian
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: accounts_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge